### ISSUE TITLE
500 error issuing credential

### ISSUE THREAD

**Issue by nick-verida** [verida/Credentials-Management-Platform#78]
When issuing a credential we get this in the logs:

```
Nest] 958098   - 06/01/2022, 12:51:56 AM   [ExceptionsHandler] Cannot read property 'schema' of undefined +24986365ms
TypeError: Cannot read property 'schema' of undefined
    at Credentials.<anonymous> (/home/ubuntu/verida-health-credential-management/backend/node_modules/@verida/verifiable-credentials/dist/credentials.js:240:35)
    at step (/home/ubuntu/verida-health-credential-management/backend/node_modules/@verida/verifiable-credentials/dist/credentials.js:44:23)
    at Object.next (/home/ubuntu/verida-health-credential-management/backend/node_modules/@verida/verifiable-credentials/dist/credentials.js:25:53)
    at /home/ubuntu/verida-health-credential-management/backend/node_modules/@verida/verifiable-credentials/dist/credentials.js:19:71
    at new Promise (<anonymous>)
    at __awaiter (/home/ubuntu/verida-health-credential-management/backend/node_modules/@verida/verifiable-credentials/dist/credentials.js:15:12)
    at Credentials.createCredentialJWT (/home/ubuntu/verida-health-credential-management/backend/node_modules/@verida/verifiable-credentials/dist/credentials.js:234:16)
    at Function.issueCredential (/home/ubuntu/verida-health-credential-management/backend/dist/helpers/VeridaHelper.js:42:50)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async CredentialService.issue (/home/ubuntu/verida-health-credential-management/backend/dist/modules/credential/credential.service.js:27:28)
```

**Comment by nick-verida** [comment]
@cmcWebCode40 
The PR above didn't fix the issue. I don't have an easy way to test this locally so can you please make sure it is working.

The error remains:
```
[Nest] 966247   - 06/02/2022, 5:48:20 AM   [ExceptionsHandler] Cannot read property 'schema' of undefined +78746ms
TypeError: Cannot read property 'schema' of undefined
    at Credentials.<anonymous> (/home/ubuntu/verida-health-credential-management/backend/node_modules/@verida/verifiable-credentials/dist/credentials.js:240:35)
    at step (/home/ubuntu/verida-health-credential-management/backend/node_modules/@verida/verifiable-credentials/dist/credentials.js:44:23)
    at Object.next (/home/ubuntu/verida-health-credential-management/backend/node_modules/@verida/verifiable-credentials/dist/credentials.js:25:53)
    at /home/ubuntu/verida-health-credential-management/backend/node_modules/@verida/verifiable-credentials/dist/credentials.js:19:71
    at new Promise (<anonymous>)
    at __awaiter (/home/ubuntu/verida-health-credential-management/backend/node_modules/@verida/verifiable-credentials/dist/credentials.js:15:12)
    at Credentials.createCredentialJWT (/home/ubuntu/verida-health-credential-management/backend/node_modules/@verida/verifiable-credentials/dist/credentials.js:234:16)
    at Function.issueCredential (/home/ubuntu/verida-health-credential-management/backend/dist/helpers/VeridaHelper.js:42:50)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async CredentialService.issue (/home/ubuntu/verida-health-credential-management/backend/dist/modules/credential/credential.service.js:27:28)
```

I didn't really understand the thing you wrote about 403 errors for those schemas - they are not giving 403 when I access them. 

In any case, if there is a problem like that it's reasonable to log on the server the exception but try to keep going. Just because one schema that isn't used when issuing the covid19 certificate is invalid it shouldn't stop that process.

**Comment by cmcWebCode40** [comment]
I actually tested the end-end to ensure it's working locally, but I will retest and record it.

**Comment by cmcWebCode40** [comment]
here is a working demo (development) https://www.loom.com/share/4b2aa1b613b646a9a45b9737cd16af5b

**Comment by cmcWebCode40** [comment]
@nick-verida, 

concerning this issue, I don't know why I have not been able to reproduce the above error, I have ensured there's no yarn linking used and investigated why this works on development and breaks on production.

I have sent multiple credentials and viewed the verified credential on the verida.network 

Like you said I would add some logging but, do you have any idea of why this could be happening?
